apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-169888398
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-169888398
    app.kubernetes.io/part-of: test-app-169888398
  name: go-169888398
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: go-169888398
status:
  loadBalancer: {}
